apiVersion: v1
kind: Secret
metadata:
  name: ca-secrets
  namespace: ca-system
  labels:
    app.kubernetes.io/part-of: web3-adult-industry-ca
type: Opaque
stringData:
  api-key: "<base64-encoded-api-key>"
  jwt-secret: "<base64-encoded-jwt-secret>"
  db-password: "<base64-encoded-db-password>"
